#Configuration for different environments

defaults: &defaults
    app_name: RevenueGrader
    short_app_name: RevenueGrader
    host: www.revenuegrader.com
    domain_host: revenuegrader.com
    support_email: support@revenuegrader.com

development:
    <<: *defaults
    host:  dev.revenuegrader.com
    facebook_app_id: '367975119899698'
    facebook_secret_key: '340c1331cddc687ce7085d849424eece'
    twitter_api_id: '0MCcStPgM8eAvlIpDZEU5g'
    twitter_secret_key: 'NTxxbMxIXqsj2m3DWBAiosJPQp7IcDtLBd4l9nKOY'
    google_api_id: '72880727859.apps.googleusercontent.com'
    google_secret_key: 'ymxlipy3Od9BaFRRzvmJOE41'
    linkedin_api_key: 'dt67gevhr7lv'
    linkedin_secret_key: 'mIc7DHX0CquGm8jt'

staging:
    <<: *defaults
    host: stage.revenuegrader.com
    facebook_app_id: '208616319240040'
    facebook_secret_key: '907b9b8444f129d1dc6d8da744bfa781'
    twitter_api_id: '80Mc8tqcacwJ07OrT8kPfw'
    twitter_secret_key: 'pBA5xmtDz5vNdEwn1buvdFJaa5HxxbGy6M8YMto0o'
    google_api_id: ''
    google_secret_key: ''

production:
    <<: *defaults
    host: www.revenuegrader.com
    facebook_app_id: '417073514990362'
    facebook_secret_key: 'aba93b297245e2a257c5c145e8b374a5'  
    twitter_api_id: 'yB7A8psK5qBUHVt3RDEjjw'
    twitter_secret_key: 'rb5GB4BqA8Ojg0kQUeG1qNxz9PKN0gtl0RKzGoN5H4'
    google_api_id: ''
    google_secret_key: ''
