#Configuration for different environments

defaults: &defaults
    app_name: RevenueGrader
    short_app_name: RevenueGrader
    host: www.revenuegrader.com
    domain_host: revenuegrader.com
    support_email: support@revenuegrader.com
    linkedin_api_key: '77rjwbnry8xj3n'
    linkedin_secret_key: '9nebekRmylzpJ4cC'

development:
    <<: *defaults
    host:  dev.revenuegrader.com
    facebook_app_id: '633909890083218'
    facebook_secret_key: 'ba427dd5d6ac8d3879d0ed4b9973c77f'
    twitter_api_id: '0MCcStPgM8eAvlIpDZEU5g'
    twitter_secret_key: 'NTxxbMxIXqsj2m3DWBAiosJPQp7IcDtLBd4l9nKOY'
    google_api_id: '150310891690-mmu7i2a07r2baft34uifcam0bgipi68k.apps.googleusercontent.com'
    google_secret_key: '_PqrR1qOya_N6pMK2RUPcqXI'

staging:
    <<: *defaults
    host: revenuegrader-staging.herokuapp.com
    facebook_app_id: '208616319240040'
    facebook_secret_key: '907b9b8444f129d1dc6d8da744bfa781'
    twitter_api_id: '80Mc8tqcacwJ07OrT8kPfw'
    twitter_secret_key: 'pBA5xmtDz5vNdEwn1buvdFJaa5HxxbGy6M8YMto0o'
    google_api_id: '427784068507-lu0cvvc3mus1rfcfj18f9l8ulit92und.apps.googleusercontent.com'
    google_secret_key: 'RWmmdJvDY6CyKDk9YSzJMtiD'

production:
    <<: *defaults
    host: revenuegrader.com
    facebook_app_id: '367975119899698'
    facebook_secret_key: '340c1331cddc687ce7085d849424eece'
    twitter_api_id: 'yB7A8psK5qBUHVt3RDEjjw'
    twitter_secret_key: 'rb5GB4BqA8Ojg0kQUeG1qNxz9PKN0gtl0RKzGoN5H4'
    google_api_id: '150310891690-mmu7i2a07r2baft34uifcam0bgipi68k.apps.googleusercontent.com'
    google_secret_key: '_PqrR1qOya_N6pMK2RUPcqXI'
