#Configuration for different environments

defaults: &defaults
    app_name: RevenueGrader
    short_app_name: RevenueGrader
    host: www.revenuegrader.com
    domain_host: revenuegrader.com
    support_email: support@revenuegrader.com

development:
    <<: *defaults
    host:  dev.revenuegrader.com
    facebook_app_id: '367975119899698'
    facebook_secret_key: '340c1331cddc687ce7085d849424eece'
    twitter_api_id: '0MCcStPgM8eAvlIpDZEU5g'
    twitter_secret_key: 'NTxxbMxIXqsj2m3DWBAiosJPQp7IcDtLBd4l9nKOY'
    google_api_id: '687896268286.apps.googleusercontent.com'
    google_secret_key: 'qJ3gKLSbbeAT3-ZShMsArias'

staging:
    <<: *defaults
    host: stage.revenue-grader.com
    facebook_app_id:
    facebook_secret_key:
    twitter_api_id:
    twitter_secret_key:
    google_api_id:
    google_secret_key:

production:
    <<: *defaults
    host: www.revenuegrader.com
    facebook_app_id:
    facebook_secret_key:
    twitter_api_id:
    twitter_secret_key:
    google_api_id:
    google_secret_key:
